### ISSUE TITLE
Update the header and footer

### ISSUE THREAD

**Issue by jenweber** [ember-learn/statusboard#24]
- [ ] sync up footer with glimmer-styleguide (and split out the styling) - @jenweber
- [ ] implement components once they ship

**Comment by locks** [comment]
https://github.com/ember-learn/ember-styleguide

**Comment by prasannavijayan** [comment]
I'll work on this.

**Comment by jenweber** [comment]
Closed, looks like someone did this work in another issue/PR. But thanks anyway!
