### ISSUE TITLE
Remove jQuery

### ISSUE THREAD

**Issue by rwwagner90** [ember-learn/statusboard#34]
We want to make sure we remove jQuery to cut down on bloat.

**Comment by rwwagner90** [comment]
This seems to be completed.

**Comment by josemarluedke** [comment]
Isn't jQuery already removed? https://github.com/ember-learn/statusboard/blob/master/ember-cli-build.js#L15

**Comment by rwwagner90** [comment]
@josemarluedke yes, I said this seems to be completed.

**Comment by josemarluedke** [comment]
@rwwagner90 I'm sorry, I miss read it.
