### ISSUE TITLE
Add Ember Engines to statusboard

### ISSUE THREAD

**Issue by yohanmishkin** [ember-learn/statusboard#39]
Are engines worthy of being on the statusboard, being pre-v1.0?

**Comment by yohanmishkin** [comment]
If so, happy to add it.

**Comment by Gaurav0** [comment]
We might want to add additional, separate items for:

1. Testing Story
2. Lazy Loading

**Comment by MelSumner** [comment]
Link to #49

**Comment by mike183** [comment]
I guess this can be closed now with #113 being merged?

**Comment by Gaurav0** [comment]
I don't have permission to close.

**Comment by yohanmishkin** [comment]
Closing! Thanks!
