### ISSUE TITLE
New QUnit testing API

### ISSUE THREAD

**Issue by SergeAstapov** [ember-learn/statusboard#8]
Does it deserve it's own place in status board?

[RFC](https://github.com/emberjs/rfcs/blob/master/text/0230-simplify-qunit-testing-api.md) has been merged awhile ago  and there is [WIP PR to ember-qunit](https://github.com/emberjs/ember-qunit/pull/258)

**Comment by villander** [comment]
@locks we can close this issue?

**Comment by SergeAstapov** [comment]
Closing as it's already shipped.

**Comment by villander** [comment]
@locks because new testing API is this https://github.com/ember-learn/statusboard/pull/27

https://dockyard.com/blog/2018/01/11/modern-ember-testing

**Comment by SergeAstapov** [comment]
@locks @villander sorry if this is confusing.

Initial idea was list "New QUnit testing style" in statusboard.

Since it's already available - I closed the ticket.

@locks if you find it still helpful to add "New QUnit testing style" to statusboard - I can add a PR with that change

**Comment by locks** [comment]
> @locks if you find it still helpful to add "New QUnit testing style" to statusboard - I can add a PR with that change

Yes, things don't disappear from the status board once they're shipped. How do you know they're shipped? :P
